### ISSUE TITLE
"Project Timetable" side not responsed

### ISSUE THREAD

**Issue by Seqat** [FlameOfIgnis/bdWeb#22]
when we clicked the project page without logged in, the site is show not response error.

 
![image](https://user-images.githubusercontent.com/37043095/38527739-1b53d9fe-3c65-11e8-8e26-f5db6285293e.png)

**Comment by FlameOfIgnis** [comment]
Server response: 
![image](https://user-images.githubusercontent.com/16636092/38546784-3dfc2384-3cb6-11e8-8da0-2d9be6c88988.png)

**Comment by FlameOfIgnis** [comment]
Solved at [180817b](https://github.com/FlameOfIgnis/bdWeb/commit/180817b85240b6ebea697ae0286acb866351b390)
