### ISSUE TITLE
"drag and drop" problem

### ISSUE THREAD

**Issue by Seqat** [FlameOfIgnis/bdWeb#30]
when ı try to drag a file in the drop zone and pull back, the green side is stay green.
![image](https://user-images.githubusercontent.com/37043095/38707556-7a9ff238-3eba-11e8-8c39-21c545a34b4c.png)

**Comment by FlameOfIgnis** [comment]
Cant really solve because of browser side security restrictions, however, made it less noticeable. When you exit the box, it turns red. If you dont enter again in 2 seconds, goes back to grey. If you go in the box again, it resets to green.
